-- SYSTEM: AWAKEN V5.1
-- In Supabase SQL Editor ausführen.
-- Danach Authentication -> Providers: Email und optional Anonymous aktivieren.
-- Im Browser NUR die Publishable Key verwenden, niemals service_role/secret.

create table if not exists public.hunter_profiles (
 user_id uuid primary key references auth.users(id) on delete cascade,
 name text not null default 'Hunter',
 level int not null default 1 check(level>=1),
 xp int not null default 0 check(xp>=0),
 training int not null default 0 check(training>=0),
 streak int not null default 0 check(streak>=0),
 coins int not null default 0 check(coins>=0),
 str int not null default 1 check(str>=1),
 agi int not null default 1 check(agi>=1),
 vit int not null default 1 check(vit>=1),
 "end" int not null default 1 check("end">=1),
 rank text not null default 'E' check(rank in ('E','D','C','B','A','S')),
 last_training date,
 inventory jsonb not null default '[]'::jsonb,
 achievements jsonb not null default '[]'::jsonb,
 chest_date date,
 created_at timestamptz not null default now(),
 leaderboard_score bigint generated always as
   (level::bigint*1000000 + training::bigint*1000 + xp::bigint) stored
);

create table if not exists public.quest_completions (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 quest_id text not null,
 completed_on date not null default current_date,
 created_at timestamptz not null default now(),
 unique(user_id,quest_id,completed_on)
);

alter table public.hunter_profiles enable row level security;
alter table public.quest_completions enable row level security;

drop policy if exists "leaderboard read" on public.hunter_profiles;
create policy "leaderboard read" on public.hunter_profiles
for select to anon, authenticated using (true);

drop policy if exists "own profile insert" on public.hunter_profiles;
create policy "own profile insert" on public.hunter_profiles
for insert to authenticated with check(auth.uid()=user_id);

drop policy if exists "own profile update" on public.hunter_profiles;
create policy "own profile update" on public.hunter_profiles
for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

drop policy if exists "own quest read" on public.quest_completions;
create policy "own quest read" on public.quest_completions
for select to authenticated using(auth.uid()=user_id);

revoke insert,update,delete on public.quest_completions from anon,authenticated;
grant select on public.hunter_profiles to anon,authenticated;
grant insert,update on public.hunter_profiles to authenticated;
grant select on public.quest_completions to authenticated;

create or replace view public.leaderboard as
select user_id,name,level,xp,training,streak,rank,leaderboard_score
from public.hunter_profiles
order by leaderboard_score desc, training desc, xp desc;

grant select on public.leaderboard to anon,authenticated;

create or replace function public.complete_training(p_quest_id text)
returns public.hunter_profiles
language plpgsql security definer set search_path=public
as $$
declare
 uid uuid:=auth.uid(); p public.hunter_profiles; rxp int; rc int; stat text; need int;
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 if p_quest_id not in ('push','squat','plank','run','mob') then raise exception 'Invalid quest'; end if;
 if exists(select 1 from quest_completions where user_id=uid and quest_id=p_quest_id and completed_on=current_date)
 then raise exception 'Quest already completed today'; end if;

 select * into p from hunter_profiles where user_id=uid for update;
 if p.user_id is null then insert into hunter_profiles(user_id) values(uid) returning * into p; end if;

 if p_quest_id='push' then rxp:=45;rc:=35;stat:='str';
 elsif p_quest_id='squat' then rxp:=45;rc:=35;stat:='vit';
 elsif p_quest_id='plank' then rxp:=40;rc:=30;stat:='end';
 elsif p_quest_id='run' then rxp:=55;rc:=45;stat:='agi';
 else rxp:=30;rc:=25;stat:='vit'; end if;

 insert into quest_completions(user_id,quest_id) values(uid,p_quest_id);
 p.xp:=p.xp+rxp; p.coins:=p.coins+rc; p.training:=p.training+1;
 p.streak:=case when p.last_training=current_date then p.streak
                when p.last_training=current_date-1 then p.streak+1 else 1 end;
 p.last_training:=current_date;

 if stat='str' then p.str:=p.str+1;
 elsif stat='agi' then p.agi:=p.agi+1;
 elsif stat='vit' then p.vit:=p.vit+1;
 else p."end":=p."end"+1; end if;

 loop
  need:=round(120*power(1.075,p.level-1));
  exit when p.xp<need;
  p.xp:=p.xp-need; p.level:=p.level+1;
 end loop;

 p.rank:=case
  when p.level>=100 and p.training>=300 and p.streak>=90 then 'S'
  when p.level>=70 and p.training>=150 then 'A'
  when p.level>=45 and p.training>=80 then 'B'
  when p.level>=25 and p.training>=35 then 'C'
  when p.level>=10 and p.training>=10 then 'D'
  else 'E' end;

 update hunter_profiles set level=p.level,xp=p.xp,training=p.training,streak=p.streak,
 coins=p.coins,str=p.str,agi=p.agi,vit=p.vit,"end"=p."end",rank=p.rank,last_training=p.last_training
 where user_id=uid returning * into p;
 return p;
end $$;

grant execute on function public.complete_training(text) to authenticated;
